In [1]:
import pandas as pd
df=pd.read_csv('FL_insurance_sample.csv')
df

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [2]:
df.shape

(36634, 18)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36634 entries, 0 to 36633
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   policyID            36634 non-null  int64
 1   statecode           36634 non-null  object
 2   county              36634 non-null  object
 3   eq_site_limit       36634 non-null  float64
 4   hu_site_limit       36634 non-null  float64
 5   fl_site_limit       36634 non-null  float64
 6   fr_site_limit       36634 non-null  float64
 7   tiv_2011            36634 non-null  float64
 8   tiv_2012            36634 non-null  float64
 9   eq_site_deductible  36634 non-null  float64
 10  hu_site_deductible  36634 non-null  float64
 11  fl_site_deductible  36634 non-null  float64
 12  fr_site_deductible  36634 non-null  int64
 13  point_latitude      36634 non-null  float64
 14  point_longitude     36634 non-null  float64
 15  line                36634 non-null  object
 16  construction        36634 non-null  object
 17  point_granularity   36634 non-null  int64
dtypes: float64(11), int64(3), object(4)
memory usage: 5.0+ MB

In [4]:
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [5]:
df.head(10)

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
5,785275,FL,CLAY COUNTY,0.0,515035.62,0.0,0.0,515035.62,884419.17,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Masonry,3
6,995932,FL,CLAY COUNTY,0.0,19260000.00,0.0,0.0,19260000.00,20610000.00,0.0,0.0,0.0,0,30.102226,-81.713882,Commercial,Reinforced Concrete,1
7,223488,FL,CLAY COUNTY,328500.0,328500.00,328500.0,328500.0,328500.00,348374.25,0.0,16425.0,0.0,0,30.102217,-81.707146,Residential,Wood,1
8,433512,FL,CLAY COUNTY,315000.0,315000.00,315000.0,315000.0,315000.00,265821.57,0.0,15750.0,0.0,0,30.118774,-81.704613,Residential,Wood,1
9,142071,FL,CLAY COUNTY,705600.0,705600.00,705600.0,705600.0,705600.00,1010842.56,14112.0,35280.0,0.0,0,30.100628,-81.703751,Residential,Masonry,1

In [6]:
df.tail()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
36629,404309,FL,PINELLAS COUNTY,0.0,88722.0,0.0,88722.0,88722.0,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.5,1297057.5,1297057.5,1297057.5,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.9,0.0,0.0,173286.9,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.6,0.0,0.0,1499781.6,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.3,0.0,0.0,373488.3,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [10]:
df.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [15]:
numbers=[]
for i in range(100):
    if i%2==0:
        numbers.append(i)
print(numbers)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

In [49]:
df

Empty DataFrame
Columns: [Sno, Number, EvenNumber, OddNumber]
Index: []